version: '3.3'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    # enables polling mechanism so that hot-reloading works
    environment:
      - CHOKIDAR_USEPOLLING=true
    # run the container with -it flags
    stdin_open: true
    tty: true
    depends_on:
      - server
      - mongo
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
    links:
      - mongo
    labels:
      com.datadoghq.ad.check_names: '["mongo"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"server": "mongodb://datadog:airborne@%%host%%:%%port%%/redSquirrelDatabase", "replica_check": true, "additional_metrics": "metrics.commands","tcmalloc","top","collection"]}]'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
networks:
  default:
    external:
      name: red_squirrel_network
