version: '3.3'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    # enables polling mechanism so that hot-reloading works
    environment:
      - CHOKIDAR_USEPOLLING=true
    # run the container with -it flags
    stdin_open: true
    tty: true
    depends_on:
      - server
      - db
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    links:
      - db
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
